lib/lemonade_web/router.ex
defmodule LemonadeWeb.Router do
  use LemonadeWeb, :router

  import LemonadeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LemonadeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  scope "/", LemonadeWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end

  scope "/", LemonadeWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/setup", SetupLive, :index
    live "/team", TeamLive, :index
    live "/team/vacations", TeamLive, :vacations
    live "/team/vacations/:modal_id", TeamLive, :vacations
    live "/team/settings", TeamLive, :settings

    live "/settings/user", SettingsLive, :user, as: :settings
    live "/settings/profile", SettingsLive, :profile, as: :settings
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LemonadeWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", LemonadeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/register", UserRegistrationController, :new
    post "/register", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/reset_password", UserResetPasswordController, :new
    post "/reset_password", UserResetPasswordController, :create
    get "/reset_password/:token", UserResetPasswordController, :edit
    put "/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LemonadeWeb do
    pipe_through [:browser, :require_authenticated_user]

    put "/user/settings", UserSettingsController, :update
    get "/user/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", LemonadeWeb do
    pipe_through [:browser]

    delete "/logout", UserSessionController, :delete
    get "/user-confirm", UserConfirmationController, :new
    post "/users-confirm", UserConfirmationController, :create
    get "/users-confirm/:token", UserConfirmationController, :confirm
  end
end

lib/lemonade_web/controllers/user_settings_controller.ex
defmodule LemonadeWeb.UserSettingsController do
  use LemonadeWeb, :controller

  alias Lemonade.Accounts
  alias LemonadeWeb.UserAuth

  plug :assign_email_and_password_changesets

  def update(conn, %{"action" => "update_password"} = params) do
    %{"current_password" => password, "user" => user_params} = params
    user = conn.assigns.current_user

    case Accounts.update_user_password(user, password, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Password updated successfully.")
        |> put_session(:user_return_to, Routes.settings_path(conn, :user))
        |> UserAuth.log_in_user(user)

      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Something went wrong")
        |> redirect(to: Routes.settings_path(conn, :user))
    end
  end

  def confirm_email(conn, %{"token" => token}) do
    case Accounts.update_user_email(conn.assigns.current_user, token) do
      :ok ->
        conn
        |> put_flash(:info, "Email changed successfully.")
        |> redirect(to: Routes.settings_path(conn, :user))

      :error ->
        conn
        |> put_flash(:error, "Email change link is invalid or it has expired.")
        |> redirect(to: Routes.settings_path(conn, :user))
    end
  end

  defp assign_email_and_password_changesets(conn, _opts) do
    user = conn.assigns.current_user

    conn
    |> assign(:email_changeset, Accounts.change_user_email(user))
    |> assign(:password_changeset, Accounts.change_user_password(user))
  end
end

lib/lemonade_web/views/user_settings_view.ex
defmodule LemonadeWeb.UserSettingsView do
  use LemonadeWeb, :view
end

lib/lemonade_web/templates/user_settings/edit.html.eex
<h3>Change email</h3>

<%= form_for @email_changeset, Routes.user_settings_path(@conn, :update), fn f -> %>
  <%= if @email_changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :action, name: "action", value: "update_email" %>

  <%= label f, :email %>
  <%= email_input f, :email, required: true %>
  <%= error_tag f, :email %>

  <%= label f, :current_password, for: "current_password_for_email" %>
  <%= password_input f, :current_password, required: true, name: "current_password", id: "current_password_for_email" %>
  <%= error_tag f, :current_password %>

  <h2>
    <%= submit "Change email" %>
  </h2>
<% end %>

<h3>Change password</h3>

<%= form_for @password_changeset, Routes.user_settings_path(@conn, :update), fn f -> %>
  <%= if @password_changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :action, name: "action", value: "update_password" %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <%= label f, :current_password, for: "current_password_for_password" %>
  <%= password_input f, :current_password, required: true, name: "current_password", id: "current_password_for_password" %>
  <%= error_tag f, :current_password %>

  <div>
    <%= submit "Change password" %>
  </div>
<% end %>